spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/logger
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: 8080
